#!/usr/bin/env python3
"""
Konwersja plików .doc do .txt dla korpusu cybernetyki
Używa múltiple metod konwersji: docx2txt, mammoth, python-docx, textract
"""

import os
import subprocess
from pathlib import Path
import argparse

def convert_with_docx2txt(doc_path):
    """Próba konwersji przez docx2txt (najlepsze dla .docx)"""
    try:
        import docx2txt
        doc_path = Path(doc_path)
        
        # docx2txt działa głównie na .docx, ale spróbujmy
        text = docx2txt.process(str(doc_path))
        
        if text and text.strip():
            txt_path = doc_path.parent / f"{doc_path.stem}.txt"
            with open(txt_path, 'w', encoding='utf-8') as f:
                f.write(f"=== {doc_path.stem} ===\n")
                f.write(f"Converted from: {doc_path.name}\n")
                f.write("Generated by: docx2txt\n\n")
                f.write(text)
            
            return txt_path
        return None
        
    except Exception as e:
        print(f"❌ docx2txt error: {e}")
        return None

def convert_with_mammoth(doc_path):
    """Próba konwersji przez mammoth (najlepsze dla .docx)"""
    try:
        import mammoth
        doc_path = Path(doc_path)
        
        with open(doc_path, "rb") as docx_file:
            result = mammoth.extract_raw_text(docx_file)
            text = result.value
        
        if text and text.strip():
            txt_path = doc_path.parent / f"{doc_path.stem}.txt"
            with open(txt_path, 'w', encoding='utf-8') as f:
                f.write(f"=== {doc_path.stem} ===\n")
                f.write(f"Converted from: {doc_path.name}\n")
                f.write("Generated by: mammoth\n\n")
                f.write(text)
            
            return txt_path
        return None
        
    except Exception as e:
        print(f"❌ mammoth error: {e}")
        return None

def convert_with_python_docx(doc_path):
    """Próba konwersji przez python-docx (głównie .docx)"""
    try:
        from docx import Document
        doc_path = Path(doc_path)
        
        doc = Document(str(doc_path))
        text_parts = []
        
        for paragraph in doc.paragraphs:
            text_parts.append(paragraph.text)
        
        text = '\n'.join(text_parts)
        
        if text and text.strip():
            txt_path = doc_path.parent / f"{doc_path.stem}.txt"
            with open(txt_path, 'w', encoding='utf-8') as f:
                f.write(f"=== {doc_path.stem} ===\n")
                f.write(f"Converted from: {doc_path.name}\n")
                f.write("Generated by: python-docx\n\n")
                f.write(text)
            
            return txt_path
        return None
        
    except Exception as e:
        print(f"❌ python-docx error: {e}")
        return None

def convert_with_textract(doc_path):
    """Próba konwersji przez textract"""
    try:
        import textract
        doc_path = Path(doc_path)
        text = textract.process(str(doc_path)).decode('utf-8')
        
        if text and text.strip():
            txt_path = doc_path.parent / f"{doc_path.stem}.txt"
            with open(txt_path, 'w', encoding='utf-8') as f:
                f.write(f"=== {doc_path.stem} ===\n")
                f.write(f"Converted from: {doc_path.name}\n")
                f.write("Generated by: textract\n\n")
                f.write(text)
            
            return txt_path
        return None
        
    except Exception as e:
        print(f"❌ textract error: {e}")
        return None

def convert_with_libreoffice(doc_path, output_dir=None):
    """Konwertuje plik .doc do .txt używając LibreOffice"""
    doc_path = Path(doc_path)
    if output_dir is None:
        output_dir = doc_path.parent
    
    try:
        # LibreOffice konwersja: doc -> txt
        cmd = [
            'libreoffice', '--headless', '--convert-to', 'txt',
            '--outdir', str(output_dir), str(doc_path)
        ]
        
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        
        if result.returncode == 0:
            txt_file = output_dir / f"{doc_path.stem}.txt"
            return txt_file if txt_file.exists() else None
        else:
            print(f"❌ LibreOffice error: {result.stderr}")
            return None
            
    except subprocess.TimeoutExpired:
        print(f"❌ LibreOffice timeout")
        return None
    except FileNotFoundError:
        print("❌ LibreOffice not found")
        return None

def convert_doc_file(doc_path):
    """Próbuje różne metody konwersji pliku .doc"""
    doc_path = Path(doc_path)
    print(f"\n🔄 Przetwarzam: {doc_path.name}")
    
    # Sprawdź czy .txt już istnieje
    txt_file = doc_path.parent / f"{doc_path.stem}.txt"
    if txt_file.exists():
        print(f"⚠️  Plik {txt_file.name} już istnieje, pomijam")
        return True
    
    # Lista metod do wypróbowania (w kolejności preferencji)
    conversion_methods = [
        ("textract", convert_with_textract),
        ("mammoth", convert_with_mammoth),
        ("python-docx", convert_with_python_docx), 
        ("docx2txt", convert_with_docx2txt),
        ("libreoffice", convert_with_libreoffice)
    ]
    
    for method_name, method_func in conversion_methods:
        print(f"🔄 Próba z {method_name}...")
        result = method_func(doc_path)
        
        if result and result.exists():
            size = result.stat().st_size
            print(f"✅ Sukces ({method_name}): {result.name} ({size} bajtów)")
            return True
    
    print(f"❌ Wszystkie metody zawiodły dla: {doc_path.name}")
    return False

def get_available_topics():
    """Pobierz dostępne tematy"""
    topics_path = Path("TOPICS")
    if not topics_path.exists():
        return []
    
    topics = []
    for item in topics_path.iterdir():
        if item.is_dir():
            topics.append(item.name)
    
    return sorted(topics)

def find_doc_files(topic=None):
    """Znajdź pliki .doc w określonym temacie lub wszystkich tematach"""
    topics_path = Path("TOPICS")
    
    if not topics_path.exists():
        print("❌ Folder TOPICS/ nie istnieje")
        return []
    
    doc_files = []
    
    if topic:
        # Szukaj tylko w określonym temacie
        topic_path = topics_path / topic
        if not topic_path.exists():
            print(f"❌ Temat '{topic}' nie istnieje")
            available_topics = get_available_topics()
            if available_topics:
                print(f"Dostępne tematy: {', '.join(available_topics)}")
            return []
        
        doc_files.extend(list(topic_path.rglob('*.doc')))
        print(f"🔍 Szukanie plików .doc w temacie: {topic}")
    else:
        # Szukaj we wszystkich tematach
        doc_files.extend(list(topics_path.rglob('*.doc')))
        print(f"🔍 Szukanie plików .doc we wszystkich tematach")
    
    return doc_files

def main():
    """Konwertuj wszystkie pliki .doc w folderach"""
    parser = argparse.ArgumentParser(description="Konwersja plików .doc do .txt")
    parser.add_argument("-t", "--topic", help="Przetwarzaj tylko pliki z określonego tematu")
    parser.add_argument("--list-topics", action="store_true", help="Pokaż dostępne tematy")
    
    args = parser.parse_args()
    
    if args.list_topics:
        topics = get_available_topics()
        if topics:
            print("📂 Dostępne tematy:")
            for topic in topics:
                print(f"  • {topic}")
        else:
            print("❌ Nie znaleziono tematów w folderze TOPICS/")
        return
    
    if args.topic:
        print(f"📄 Konwersja plików .doc do .txt - temat: {args.topic}")
    else:
        print("📄 Konwersja plików .doc do .txt - wszystkie tematy")
    print("=" * 40)
    
    # Znajdź wszystkie pliki .doc
    doc_files = find_doc_files(args.topic)
    
    if not doc_files:
        if args.topic:
            print(f"❌ Nie znaleziono plików .doc w temacie '{args.topic}'")
        else:
            print("❌ Nie znaleziono plików .doc")
        return
    
    print(f"📁 Znaleziono {len(doc_files)} plików .doc")
    
    converted = 0
    failed = 0
    
    for doc_file in doc_files:
        if convert_doc_file(doc_file):
            converted += 1
        else:
            failed += 1
    
    print(f"\n📊 PODSUMOWANIE KONWERSJI .DOC:")
    print(f"✅ Skonwertowane: {converted}")
    print(f"❌ Nieudane: {failed}")
    print(f"📝 Razem plików .doc: {len(doc_files)}")

if __name__ == "__main__":
    main() 